{% set version = "0.10" %}

package:
  name: otwrapy
  version: {{ version }}

source:
  fn: otwrapy-{{ version }}.tar.gz
  url: https://github.com/openturns/otwrapy/archive/v{{ version }}.tar.gz
  sha256: 001f091f20c8520ca5a4f6b9ea5de4ca1ec2bc193410194365bfc2e82a544c21

build:
  number: 0
  noarch: python
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"
    - rm ${SP_DIR}/otwrapy/examples/beam/{beam,beam.exe}

requirements:
  host:
    - pip
    - python
    - setuptools
    - pytest-runner
    - numpy
    - openturns >=1.16
  run:
    - python >=3.6
    - numpy
    - joblib >=0.9.3
    - ipyparallel >=5.0.1
    - pathos >=0.2.0
    - openturns >=1.16

test:
  imports:
    - otwrapy

about:
  home: https://github.com/openturns/otwrapy
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: General purpose OpenTURNS python wrapper tools

extra:
  recipe-maintainers:
    - jschueller
    - felipeam86
