{% set version = "0.13" %}

package:
  name: otwrapy
  version: {{ version }}

source:
  fn: otwrapy-{{ version }}.tar.gz
  url: https://github.com/openturns/otwrapy/archive/v{{ version }}.tar.gz
  sha256: b19acdf8c9359fab18067d906cf2aa993a3a7d343e23683c1babb342e1f6c399

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv
    - rm ${SP_DIR}/otwrapy/examples/beam/{beam,beam.exe}

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - pytest-runner
    - numpy
    - openturns >=1.16
  run:
    - python >={{ python_min }}
    - numpy
    - joblib >=0.9.3
    - ipyparallel >=5.0.1
    - pathos >=0.2.0
    - openturns >=1.16
    - dask
    - asyncssh
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - otwrapy

about:
  home: https://github.com/openturns/otwrapy
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: General purpose OpenTURNS python wrapper tools

extra:
  recipe-maintainers:
    - jschueller
