{% set version = "0.9" %}

package:
  name: otwrapy
  version: {{ version }}

source:
  fn: otwrapy-{{ version }}.tar.gz
  url: https://github.com/openturns/otwrapy/archive/v{{ version }}.tar.gz
  sha256: 823678fb65e09df972cc6c7a65437a071659f696dfd9aefb0c3697d8d96b3fba

build:
  number: 4
  noarch: python
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"
    - rm ${SP_DIR}/otwrapy/examples/beam/{beam,beam.exe}

requirements:
  host:
    - pip
    - python
    - setuptools
    - pytest-runner
    - numpy
    - openturns 1.16*
  run:
    - python >=3.6
    - numpy
    - joblib >=0.9.3
    - ipyparallel >=5.0.1
    - pathos >=0.2.0
    - openturns 1.16*

test:
  imports:
    - otwrapy

about:
  home: https://github.com/openturns/otwrapy
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: General purpose OpenTURNS python wrapper tools

extra:
  recipe-maintainers:
    - jschueller
    - felipeam86
