# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "UOzgDoyq+XOcqMjHWFW1fGgd/8Sk1wvUp18YzVfUAT2cLAgKeS0f8MqbU2jDUdUmFqMl3tYeNE/4ubui1Q7Yqnrco6rB5bfuD+jV+zu9JMaBnieaUfZIlaIW9LYE9hVPeoiuJ2ue4hUss5NdkDRdjX5mHYh3SEBkkMS+iYxqArnGUrtl24GMoBqE6WyhOv/waeCmz0ETZaPmeG6A8Len6A2be6L7LM5S9QbZSY7fR9Qek2+fImna/CS1LjfVIrud+BuhFkCPfl/swY/U/WDddAus7h+npo1D9RyQEXbz8gFAdriyACv/XZDNlxoxQ3jMm0SSgdUT4TOHWXyBN6JvdauWOxcsA15McPcci3UDgBAXkJCGOrPNJOZbzsZTyeC0/NNOfw7DYDUf+mJ+FsJBxZuggRRDHIhuAeXRlb7QnzaJxtR2kuuCo925FVEV49xZPBrrLvbNXsqGXKShH14GMumZQmE3RkJ0990m5aEYqozjxTtphUwQoDZCA9WOqNTAcA/a7Tip4Cuk1/HP0XGwhAwJ2c8N0K29UIHCuOTx9thE+LxsLaRM9FcK3X99IQlLgBgEGhaJW9I+/RHfU77eDSZOuDxctdoG0tKUXP/LuCDgOqqaa9payyl+pcSDx1KC829MFHvOGxOFR+wQlMqmE5hybaqqsr8AEsm2XmKZ+5s="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
