travis:
  secure:
    BINSTAR_TOKEN: XAYuk+/J7NcGyHa9hOmxIhMoIOsB7zVZTG/66CrjU31BrWj/5D55wgITeRMvZTlojzoDyt/HBlyE3QnLHhBByiDg2fb4VMD8+hsITu3RVNo+VW0w7f0Oai30noTUCURofMUaiA6lQdp2Hujcvbwe6dKsEZks/CK4SLZfIvSWcuhfkVjWRlfAXLbw8k6AMqg43N1ZCbkHDsjFP0AIP5UtNzmpZri/5DUbS59rYcGsMkK8YMMQ8kCMD5iy1Qr/vRmizeYlJYDNNNr/Iiis+JFWYZSqeMXv2Mf+qAhhjwvIlhsxSQfzRsLZvgLaQsSQSNM3zHMXWmYRwh4aWrCg5YFRPbTMxRELvDvUC+5Vq+LOjuVZkDBwzm3mDRJn+yC+MpGAFQNcIWQ2QO7zGJ/EGXq0TnNAmIHBAwF4DI2Vm5qieQeSRcDg1xfKCrT3kgELMMo4iC1ldA1QpaZDiW7XMu2HjiexvMvPmmULqhBytSvZW5GRicsQLTPke9y7BO+8NIaX8I0EvlIvYays1+E9xwtytVbp7PhxsIqyFSBy9P5UHBp2aHdfllOR7g06hRwaVZWpObN5pefUNhGXFSm3762JTnq1B5SKUPg+NHgUMFPXLYXx8dHCpybrbcBcBfOFv8qR+DZCg3/a1TvNxXFyQUlVkFqUR2HBFh8yFm7Ke0L9n5E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
