travis:
  secure:
    BINSTAR_TOKEN: wgfHUsrXsbXVzreNo+7Qv7QsWgUV7wUJT3lJJXsSrrCiKvsC9Z67zRuT34O47EdDL5JUfP81ig8+d+XUegb0THghs1j+HU8JTpdJfVBI9BIDANXAn0sDC2rSmQ6fKbgrL6odWknOoUjtfv206+dPWeeOAyNshm4dV5SEBsskP3IW3X4YFaik/YUHm58+2zQF3iOqbd5M5RLg3XwdJrShzoFLefRsl4FeeE6ffAGT7numCnyYKyqtOG+tRiVuJ6jG9TMMOdUFpxsw4Z2Woi8navwblXFx6WAxn0TSc+mtIBpyltAR0wFcSMzPSTh8Ard2nnJPHrZdn4Pf4KugnLIlKK9ea3H3Ckvasvc/AnUwfq7ZtuOg1pmSxYGAkJI1R41bJgkzicXnp+IGdtCAwEt1Wcm5hjQoImJTyG/Uq621BLUsnCogyMsVG7qEjhDQDWtA0WLQvZeeg56KFgmAgKfcE6xEGdpRMYRrlPPbodnIxUF9YC3nqiK0WfpepwTo3nI2R4XauAF4jJLTdnZmbGT/sKgy7ZWj7Uelqyqi77FEKkEl7gzLbi70cj0KgYjjnoFPJc9Wspxhci7PSVofD1c87XiQo1JEsb39rBPhAQTMyXbYV1zOWR87KJnU7hfLbm3XiualpTznJAnLpU/n7hXWRUBwcvR1X7AwM6SKyfp19BE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
